**Choco Crunch Analytics — Feature Engineering**

**Retrieve the Cleaned DataFrame**

The cleaned DataFrame from the previous data exploration and cleaning stage is retrieved using the IPython `%store` mechanism.

This allows the feature engineering process to continue without repeating the data loading and cleaning steps.

In [1]:
%store -r df

**Select Relevant Nutritional Features**

A list of relevant nutritional and product-quality features is defined for further processing.

These features include energy, carbohydrates, sugars, fats, proteins, fiber, salt, sodium, NOVA classification, nutrition score, and the estimated percentage of fruits, vegetables, and nuts.

Selecting the relevant columns helps create a focused dataset for the subsequent analysis.

In [2]:
main_columns = [
    'nutriments.energy-kcal_value',
    'nutriments.energy-kj_value',
    'nutriments.carbohydrates_value',
    'nutriments.sugars_value',
    'nutriments.fat_value',
    'nutriments.saturated-fat_value',
    'nutriments.proteins_value',
    'nutriments.fiber_value',
    'nutriments.salt_value',
    'nutriments.sodium_value',
    'nutriments.nova-group',
    'nutriments.nutrition-score-fr',
    'nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g',
]

In [3]:
## Create the Main Feature DataFrame

## The selected nutritional features are extracted from the cleaned DataFrame and copied into a new DataFrame named `df_main`.

## Creating a separate DataFrame allows the feature engineering process to be performed while keeping the original cleaned DataFrame available.

df_main = df[main_columns].copy()

In [4]:
## Verify the Selected Features

## The column names of `df_main` are displayed to verify that the required nutritional features have been selected correctly.

df_main.columns

Index(['nutriments.energy-kcal_value', 'nutriments.energy-kj_value',
       'nutriments.carbohydrates_value', 'nutriments.sugars_value',
       'nutriments.fat_value', 'nutriments.saturated-fat_value',
       'nutriments.proteins_value', 'nutriments.fiber_value',
       'nutriments.salt_value', 'nutriments.sodium_value',
       'nutriments.nova-group', 'nutriments.nutrition-score-fr',
       'nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g'],
      dtype='str')

In [5]:
## Inspect the Selected Data

## The contents of `df_main` are displayed to inspect the selected nutritional features before further processing.

df_main

,nutriments.energy-kcal_value,nutriments.energy-kj_value,nutriments.carbohydrates_value,nutriments.sugars_value,nutriments.fat_value,nutriments.saturated-fat_value,nutriments.proteins_value,nutriments.fiber_value,nutriments.salt_value,nutriments.sodium_value,nutriments.nova-group,nutriments.nutrition-score-fr,nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g
0,0.0,20.0,42.0,14.0,0.0,0.0,0.0,0.0,0.00000,0.000000,NaN,1.0,0.0
1,97.0,406.0,9.4,NaN,3.0,NaN,8.0,NaN,NaN,NaN,3.0,NaN,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00000,26.000000,NaN,0.0,0.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00000,26.000000,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00508,0.002032,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12092,228.0,965.0,43.0,2.9,1.2,0.2,10.0,2.4,0.68000,0.272000,4.0,1.0,0.0
12093,32.0,134.0,5.7,4.8,1.0,0.1,0.5,0.5,0.14000,0.056000,3.0,5.0,0.0
12094,42.0,179.0,9.2,8.2,0.5,0.1,0.7,0.5,0.01000,0.004000,1.0,4.0,100.0
12095,428.0,1791.0,57.0,5.0,15.0,2.9,11.0,14.0,0.10000,0.040000,4.0,-1.0,0.0
12096,341.0,1442.0,51.0,13.0,11.0,3.8,8.6,2.2,0.82000,0.328000,4.0,14.0,0.0

In [6]:
## Check Missing Values in the Selected Features

## The percentage of missing values is calculated for each selected feature.

## This helps identify the extent of missing information in the nutritional variables before applying a strategy to handle those values.

(df_main.isnull().sum() / len(df)) * 100

nutriments.energy-kcal_value                                         4.786557
nutriments.energy-kj_value                                          45.030977
nutriments.carbohydrates_value                                       4.718662
nutriments.sugars_value                                              6.390563
nutriments.fat_value                                                 4.540440
nutriments.saturated-fat_value                                       7.061020
nutriments.proteins_value                                            4.616821
nutriments.fiber_value                                              30.213019
nutriments.salt_value                                                7.383519
nutriments.sodium_value                                              7.383519
nutriments.nova-group                                                9.165747
nutriments.nutrition-score-fr                                       12.450140
nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g     4.650768
dtype: float64

In [7]:
## Handle Missing Numerical Values

## Missing values in the selected nutritional features are filled using the median of each respective column.

## The median is used because it is less sensitive to extreme values and outliers compared with the mean, making it suitable for nutritional variables that may have skewed distributions.

for col in main_columns:
    median_val = df_main[col].median()  # median is robust to outliers
    df_main[col] = df_main[col].fillna(median_val)

In [8]:
## Verify Missing Values After Imputation

## The missing-value percentage is calculated again after median imputation to verify the effect of the missing-value treatment.

(df_main.isnull().sum() / len(df)) * 100

nutriments.energy-kcal_value                                        0.0
nutriments.energy-kj_value                                          0.0
nutriments.carbohydrates_value                                      0.0
nutriments.sugars_value                                             0.0
nutriments.fat_value                                                0.0
nutriments.saturated-fat_value                                      0.0
nutriments.proteins_value                                           0.0
nutriments.fiber_value                                              0.0
nutriments.salt_value                                               0.0
nutriments.sodium_value                                             0.0
nutriments.nova-group                                               0.0
nutriments.nutrition-score-fr                                       0.0
nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g    0.0
dtype: float64

In [9]:
## Inspect the Imputed Data

## The first few records of `df_main` are displayed to verify the structure and values of the feature-engineered dataset after handling the missing nutritional values.

df_main.head()

,nutriments.energy-kcal_value,nutriments.energy-kj_value,nutriments.carbohydrates_value,nutriments.sugars_value,nutriments.fat_value,nutriments.saturated-fat_value,nutriments.proteins_value,nutriments.fiber_value,nutriments.salt_value,nutriments.sodium_value,nutriments.nova-group,nutriments.nutrition-score-fr,nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g
0,0.0,20.0,42.0,14.0,0.0,0.0,0.0,0.0,0.00000,0.000000,4.0,1.0,0.0
1,97.0,406.0,9.4,4.1,3.0,1.4,8.0,2.5,0.37250,0.149000,3.0,7.0,0.0
2,242.0,1189.0,15.1,4.1,6.2,1.4,5.7,2.5,65.00000,26.000000,4.0,0.0,0.0
3,242.0,1189.0,15.1,4.1,6.2,1.4,5.7,2.5,65.00000,26.000000,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00508,0.002032,4.0,0.0,0.0

**Create Sugar-to-Carbohydrate Ratio**

A new feature, `sugar_to_carb_ratio`, is created by calculating the ratio of sugar content to total carbohydrate content.

This derived feature provides an additional measure of how much of the total carbohydrate content is contributed by sugars.

The resulting missing values are replaced with `0`, which also safely handles cases where the carbohydrate value is zero and the division produces an undefined result.

In [10]:
# Calculate ratio of sugar to total carbohydrates
df['nutriments.sugar_to_carb_ratio'] = df['nutriments.sugars_value'] / df['nutriments.carbohydrates_value']

# Handle divide-by-zero safely (if carbohydrates = 0)
df['nutriments.sugar_to_carb_ratio'] = df['nutriments.sugar_to_carb_ratio'].fillna(0)

C:\Users\Meiappan\AppData\Local\Temp\ipykernel_12684\1985450829.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['nutriments.sugar_to_carb_ratio'] = df['nutriments.sugars_value'] / df['nutriments.carbohydrates_value']

**Create Calorie Categories**

A categorical feature named `calorie_category` is created from the energy value in kilocalories.

Products are grouped into three categories:

- **Low** — Less than 100 kcal
- **Moderate** — Between 100 and 200 kcal
- **High** — Greater than 200 kcal

This converts the continuous calorie value into an easy-to-interpret categorical feature.

In [11]:
def calorie_category(kcal):
    if kcal < 100:
        return 'Low'
    elif 100 <= kcal <= 200:
        return 'Moderate'
    else:
        return 'High'

df['nutriments.calorie_category'] = df['nutriments.energy-kcal_value'].apply(calorie_category)

C:\Users\Meiappan\AppData\Local\Temp\ipykernel_12684\2869951507.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['nutriments.calorie_category'] = df['nutriments.energy-kcal_value'].apply(calorie_category)

**Create Sugar Categories**

A categorical feature named `sugar_category` is created based on the sugar content of each product.

The products are grouped into three categories:

- **Low Sugar** — Less than 5
- **Moderate Sugar** — Between 5 and 15
- **High Sugar** — Greater than 15

This feature makes it easier to categorize and compare products based on their sugar content.

In [12]:
def sugar_category(sugar):
    if sugar < 5:
        return 'Low Sugar'
    elif 5 <= sugar <= 15:
        return 'Moderate Sugar'
    else:
        return 'High Sugar'

df['nutriments.sugar_category'] = df['nutriments.sugars_value'].apply(sugar_category)

C:\Users\Meiappan\AppData\Local\Temp\ipykernel_12684\2773449110.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['nutriments.sugar_category'] = df['nutriments.sugars_value'].apply(sugar_category)

**Identify Ultra-Processed Products**

A binary categorical feature named `is_ultra_processed` is created using the NOVA food classification.

Products with a NOVA group value of `4` are classified as **Yes**, indicating that they are ultra-processed. Other values are classified as **No**.

This feature can be used to analyze the relationship between ultra-processing and the nutritional characteristics of chocolate products.

In [13]:
df['nutriments.is_ultra_processed'] = df['nutriments.nova-group'].apply(lambda x: 'Yes' if x == 4 else 'No')

C:\Users\Meiappan\AppData\Local\Temp\ipykernel_12684\1564851873.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['nutriments.is_ultra_processed'] = df['nutriments.nova-group'].apply(lambda x: 'Yes' if x == 4 else 'No')

**Combine Product and Derived Features**

Additional product-identification and engineered features are added to `df_main`.

These include:

- Product code
- Product name
- Brand
- Sugar-to-carbohydrate ratio
- Calorie category
- Sugar category
- Ultra-processed classification

This combines the selected nutritional variables with the product information and newly created features into a single analysis-ready DataFrame.

In [14]:
# Columns to move from df to df_main
additional_columns = [
    'code',           # product_code
    'product_name',   # product_name
    'brands',         # brand
    'nutriments.sugar_to_carb_ratio',
    'nutriments.calorie_category',
    'nutriments.sugar_category',
    'nutriments.is_ultra_processed'    
]

for col in additional_columns:
    df_main[col] = df[col]

# Verify
df_main.head()

,nutriments.energy-kcal_value,nutriments.energy-kj_value,nutriments.carbohydrates_value,nutriments.sugars_value,nutriments.fat_value,nutriments.saturated-fat_value,nutriments.proteins_value,nutriments.fiber_value,nutriments.salt_value,nutriments.sodium_value,nutriments.nova-group,nutriments.nutrition-score-fr,nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g,code,product_name,brands,nutriments.sugar_to_carb_ratio,nutriments.calorie_category,nutriments.sugar_category,nutriments.is_ultra_processed
0,0.0,20.0,42.0,14.0,0.0,0.0,0.0,0.0,0.00000,0.000000,4.0,1.0,0.0,6111035000430,Sidi Ali,Sidi Ali,0.333333,Low,Moderate Sugar,No
1,97.0,406.0,9.4,4.1,3.0,1.4,8.0,2.5,0.37250,0.149000,3.0,7.0,0.0,6111242100992,Perly,Jaouda,0.000000,Low,High Sugar,No
2,242.0,1189.0,15.1,4.1,6.2,1.4,5.7,2.5,65.00000,26.000000,4.0,0.0,0.0,6111035002175,Sidi Ali,sidi ali,0.000000,High,High Sugar,No
3,242.0,1189.0,15.1,4.1,6.2,1.4,5.7,2.5,65.00000,26.000000,1.0,0.0,0.0,6111035000058,Eau minérale naturelle,"Les Eaux Minérales d'oulmès,Sidi Ali",0.000000,High,High Sugar,No
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00508,0.002032,4.0,0.0,0.0,6111252421568,اكوافينا,AQUAFINA,0.000000,Low,Low Sugar,No

In [15]:
## Check Missing Values in the Final Feature Set

## The missing-value percentage is calculated again after adding the product and derived features.

## This provides a final check of missing information before the columns are renamed and the dataset is exported.

(df_main.isnull().sum() / len(df)) * 100

nutriments.energy-kcal_value                                        0.0
nutriments.energy-kj_value                                          0.0
nutriments.carbohydrates_value                                      0.0
nutriments.sugars_value                                             0.0
nutriments.fat_value                                                0.0
nutriments.saturated-fat_value                                      0.0
nutriments.proteins_value                                           0.0
nutriments.fiber_value                                              0.0
nutriments.salt_value                                               0.0
nutriments.sodium_value                                             0.0
nutriments.nova-group                                               0.0
nutriments.nutrition-score-fr                                       0.0
nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g    0.0
code                                                                0.0
product_name                                                        0.0
brands                                                              0.0
nutriments.sugar_to_carb_ratio                                      0.0
nutriments.calorie_category                                         0.0
nutriments.sugar_category                                           0.0
nutriments.is_ultra_processed                                       0.0
dtype: float64

In [16]:
## Review the Final Feature Columns

## The current column names are displayed to review all nutritional, product, and engineered features included in `df_main` before renaming them into cleaner names.

df_main.columns

Index(['nutriments.energy-kcal_value', 'nutriments.energy-kj_value',
       'nutriments.carbohydrates_value', 'nutriments.sugars_value',
       'nutriments.fat_value', 'nutriments.saturated-fat_value',
       'nutriments.proteins_value', 'nutriments.fiber_value',
       'nutriments.salt_value', 'nutriments.sodium_value',
       'nutriments.nova-group', 'nutriments.nutrition-score-fr',
       'nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g',
       'code', 'product_name', 'brands', 'nutriments.sugar_to_carb_ratio',
       'nutriments.calorie_category', 'nutriments.sugar_category',
       'nutriments.is_ultra_processed'],
      dtype='str')

In [17]:
## Rename Columns for a Clean Data Structure

## The original API-based column names are replaced with cleaner, database-friendly names.

## Special characters such as periods and hyphens are replaced with underscores to make the column names easier to work with in Python, PostgreSQL, and SQL queries.

## The renamed columns also provide clearer and more consistent names for the final analytical dataset.

    
df_main = df_main.rename(columns={
    # Nutrient columns
    'nutriments.energy-kcal_value': 'energy_kcal_value',
    'nutriments.energy-kj_value': 'energy_kj_value',
    'nutriments.carbohydrates_value': 'carbohydrates_value',
    'nutriments.sugars_value': 'sugars_value',
    'nutriments.fat_value': 'fat_value',
    'nutriments.saturated-fat_value': 'saturated_fat_value',
    'nutriments.proteins_value': 'proteins_value',
    'nutriments.fiber_value': 'fiber_value',
    'nutriments.salt_value': 'salt_value',
    'nutriments.sodium_value': 'sodium_value',
    'nutriments.nova-group': 'nova_group',
    'nutriments.nutrition-score-fr': 'nutrition_score_fr',
    'nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g':
        'fruits_vegetables_nuts_estimate_from_ingredients_100g',
    
    # Product identifiers and derived columns
    'code': 'product_code',  # product_code (already clean, but included for clarity)
    'product_name': 'product_name',
    'brands': 'brands',
    'nutriments.sugar_to_carb_ratio': 'sugar_to_carb_ratio',
    'nutriments.calorie_category': 'calorie_category',
    'nutriments.sugar_category': 'sugar_category',
    'nutriments.is_ultra_processed': 'is_ultra_processed'
})

In [18]:
## Verify the Renamed Columns

## The column names are displayed again to verify that the feature names have been successfully converted into the cleaned naming convention.

df_main.columns

Index(['energy_kcal_value', 'energy_kj_value', 'carbohydrates_value',
       'sugars_value', 'fat_value', 'saturated_fat_value', 'proteins_value',
       'fiber_value', 'salt_value', 'sodium_value', 'nova_group',
       'nutrition_score_fr',
       'fruits_vegetables_nuts_estimate_from_ingredients_100g', 'product_code',
       'product_name', 'brands', 'sugar_to_carb_ratio', 'calorie_category',
       'sugar_category', 'is_ultra_processed'],
      dtype='str')

In [19]:
## Export the Final Dataset

## The completed feature-engineered DataFrame is exported as `chococrunch_final.csv`.

## This file contains the selected nutritional variables, product information, and derived features with cleaned column names.

## The resulting dataset is prepared for the next stage of the project, where it can be loaded into PostgreSQL for SQL-based business analysis.

df_main.to_csv("chococrunch_final.csv", index=False)

In [20]:
## Store the Final DataFrame

## The final feature-engineered DataFrame is stored using the IPython `%store` command so that it can be retrieved in a subsequent Jupyter Notebook without repeating the feature engineering process.

%store df_main

Stored 'df_main' (DataFrame)